### PR TITLE
Cleanup brackets and inflections

### PR DESCRIPTION
**Pull request by cyriaka90**
Cleanup inflections with brackets like "ραματευτή]" or "(συγχωρώ→ )" or "[[]]" or "[[{{{2}}}ίου]]".
And fix declension of παράς.

(Some) Wiktionary entries for reference:
παράς https://en.wiktionary.org/wiki/%CF%80%CE%B1%CF%81%CE%AC%CF%82
φωνήεν https://en.wiktionary.org/wiki/%CF%86%CF%89%CE%BD%CE%AE%CE%B5%CE%BD
οξύ https://en.wiktionary.org/wiki/%CE%BF%CE%BE%CF%8D
φωνήεν https://en.wiktionary.org/wiki/%CE%BD%CF%84%CE%BF%CF%85%CE%B6%CE%AF%CE%BD%CE%B1

### CODE REVIEW

**Comment by aryamccarthy** [comment]
Hi, is the dash meant to indicate a paradigmatic gap? I'd rather exclude the row entirely if the word form doesn't exist.

**Comment by cyriaka90** [comment]
Hi,
yes, it seems so. In wiktionary it's just a dash like in this table: https://en.wiktionary.org/wiki/%CE%BD%CF%84%CE%BF%CF%85%CE%B6%CE%AF%CE%BD%CE%B1 therefore I kept it like this.
But I also think excluding the row would make sense. Shall I just update the pull request with the deletions?

**Comment by aryamccarthy** [comment]
Could you please?

-am

**Comment by cyriaka90** [comment]
No problem, I deleted them in the last commit. :)

**Pull request merged**
